Controllers/PickUpMedsController.cs
using ClinicalApp.Data;
using ClinicalApp.Interface;
using ClinicalApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ClinicalApp.Controllers
{
    public class PickUpMedsController : Controller
    {

        private readonly IPuckUpMedicationRepository _meds;
        private readonly DatabaseContext _context;

        public PickUpMedsController(IPuckUpMedicationRepository meds, DatabaseContext context)
        {
            _meds = meds;
            _context = context;
        }

        // GET: PickUpMedsController
        public async Task<IActionResult> Index()
        {
            List<PickUpMedication> meds = _meds.GetAll();
            return View(meds);
        }

        // GET: PickUpMedsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PickUpMedsController/Create
        public IActionResult Create()
        {
            ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "PatientFirstName");
            return View();
        }

        // POST: PickUpMedsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MedsId,PatientId, MedicationOder, MedicationSubtotal, PickupDate, MediationStatus, Comments, Payment, PatientFullName, CoolectorFullNames, PlhoneNumbers")] PickUpMedication meds)
        {
            _meds.Create(meds);
            return RedirectToAction(nameof(Index));
        }

        // GET: PickUpMedsController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if(id == null)
            {
                return NotFound();
            }
            
            PickUpMedication meds = _meds.GetbyId(id);
            if(meds == null)
            {
                return NotFound();
            }
            ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "PatientFirstName", meds.PatientId);
            return View(meds);
        }

        // POST: PickUpMedsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MedsId, PatientId, MedicationOder, MedicationSubtotal, PickupDate, MediationStatus, Comments, Payment, PatientFullName, CoolectorFullNames, PlhoneNumbers")] PickUpMedication meds)
        {
            if(id != meds.MedsId)
            {
                return NotFound();
            }

            _meds.Update(meds);
            return RedirectToAction(nameof(Index));
            ViewData["PatientId"] = new SelectList(_context.Patients, "PatientId", "PatientFirstName", meds.PatientId);
            return View(meds);
        }
        
        // GET: PickUpMedsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PickUpMedsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/PickUpMeds/Edit.cshtml
@model ClinicalApp.Models.PickUpMedication
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>

.b-example-divider {
  flex-shrink: 0;
  width: 1.5rem;
  height: 100vh;
  background-color: rgba(0, 0, 0, .1);
  border: solid rgba(0, 0, 0, .15);
  border-width: 1px 0;
  box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
}

.bi {
  vertical-align: -.125em;
  pointer-events: none;
  fill: currentColor;
}

.dropdown-toggle { outline: 0; }

.nav-flush .nav-link {
  border-radius: 0;
}

.btn-toggle {
  display: inline-flex;
  align-items: center;
  padding: .25rem .5rem;
  font-weight: 600;
  color: rgba(0, 0, 0, .65);
  background-color: transparent;
  border: 0;
}
.btn-toggle:hover,
.btn-toggle:focus {
  color: rgba(0, 0, 0, .85);
  background-color: #d2f4ea;
}

.btn-toggle::before {
  width: 1.25em;
  line-height: 0;
  content: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='rgba%280,0,0,.5%29' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M5 14l6-6-6-6'/%3e%3c/svg%3e");
  transition: transform .35s ease;
  transform-origin: .5em 50%;
}

.btn-toggle[aria-expanded="true"] {
  color: rgba(0, 0, 0, .85);
}
.btn-toggle[aria-expanded="true"]::before {
  transform: rotate(90deg);
}

.btn-toggle-nav a {
  display: inline-flex;
  padding: .1875rem .5rem;
  margin-top: .125rem;
  margin-left: 1.25rem;
  text-decoration: none;
}
.btn-toggle-nav a:hover,
.btn-toggle-nav a:focus {
  background-color: #d2f4ea;
}

.scrollarea {
  overflow-y: auto;
}

.fw-semibold { font-weight: 600; }
.lh-tight { line-height: 1.25; }

img{
    height: 125px;
    width: 125px;
    border-radius: 50px;
}

.grids{
    display: flex;
}
</style>


 <div class="grids">
     <div>
         <div class="flex-shrink-0 p-3 bg-dark" style="width: 280px; height: 100%;">
    <a asp-controller="Home" asp-action="Index" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-5 fw-semibold btn btn-success">L.H.M.S</span>
      <br /> 
    </a>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <a asp-controller="Dashboard" asp-action="Index" class="btn btn-outline-light">
          Home
        </a>
      </li>
     </ul>
      <ul class="btn-toggle-nav text-dark list-unstyled fw-normal pb-1 small">
            <li><a asp-controller="UserRole" asp-action="Index" class="link-light rounded"><i class="bi bi-people-fill"></i>&nbsp;&nbsp;Employees</a></li>
            <li><a asp-controller="Patient" asp-action="Index" class="link-light rounded"><i class="bi bi-hospital"></i>&nbsp;&nbsp;Patients</a></li>
            <li><a asp-controller="Chronic_Desease" asp-action="Index" class="link-light rounded"><i class="fa fa-bed"></i>&nbsp;&nbsp;Patient on merdication in hospital</a></li>
            

            <li><a asp-controller="Paramedic" asp-action="Index" class="link-light rounded"><i class="fas fa-ambulance"></i>&nbsp;&nbsp;Paramedics</a></li>
            <li><a asp-controller="Doctors" asp-action="Index"  class="link-light rounded"><i class="fas fa-user-md"></i>&nbsp;&nbsp;Doctors</a></li>
            <li><a asp-controller="Admin" asp-action="Index"  class="link-light rounded"><i class="bi bi-person-workspace"></i>&nbsp;&nbsp;Admin</a></li>
            <li><a asp-controller="IT" asp-action="Index" class="link-light rounded"><i class="bi bi-laptop"></i>&nbsp;&nbsp;IT</a></li>
            <li><a asp-controller="HR" asp-action="Index" class="link-light rounded"><i class="bi bi-person-check-fill"></i>&nbsp;&nbsp;HR</a></li>
             <li><a asp-controller="Clearner" asp-action="" class="link-light rounded"><i class="fas fa-hands-wash"></i>&nbsp;&nbsp;Cleaner</a></li>
            <li><a asp-controller="Nurse" asp-action="Index" class="link-light rounded"><i class="fas fa-user-nurse"></i>&nbsp;&nbsp;Nurses</a></li>
            <li><a asp-controller="Doctors" asp-action="Create" class="link-light rounded"><i class="fas fa-user-plus"></i>&nbsp;&nbsp;Add a Doctor</a></li>
            <li><a asp-controller="Finance" asp-action="Index" class="link-light rounded"><i class="bi bi-cash-coin"></i>&nbsp;&nbsp;Finance</a></li>
            <li><a asp-controller="Manager" asp-action="Index" class="link-light rounded"><i class="bi bi-list-task"></i>&nbsp;&nbsp;Management</a></li>
            <li><a asp-controller="Porter" asp-action="Index" class="link-light rounded"><i class="fa-solid fa-skull-crossbones"></i>&nbsp;&nbsp;Porter</a></li>

            <li><a asp-controller="P_Hospital" asp-action="Index" class="link-light rounded"><i class="fa fa-bed"></i>&nbsp;&nbsp;Patient on merdication of hospital</a></li>
            <li><a asp-controller="InComplete" asp-action="Index" class="link-light rounded"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>&nbsp;&nbsp;Patientwho didnt complete treatment</a></li>
            <li><a asp-controller="PickUpMeds" asp-action="Index" class="link-light rounded"><i class="bi bi-collection-fill"></i>&nbsp;&nbsp;Collection</a></li>
             <li><a asp-controller="MaleWards" asp-action="Index" class="link-light rounded"><i class="fas fa-male"></i>&nbsp;&nbsp;Male Ward</a></li>
            <li><a asp-controller="FemaleWards" asp-action="Index" class="link-light rounded"><i class="fas fa-female"></i>&nbsp;&nbsp;Female Ward</a></li>
            <li><a asp-controller="MetinityWard" asp-action="Index" class="link-light rounded"><i class="fas fa-baby"></i>&nbsp;&nbsp;Metinity Ward</a></li>
           
             

       
      <li class="border-top my-3"></li>
     @* <li class="mb-1">
        <button class="btn btn-toggle align-items-center bg-danger text-light rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
          Account
        </button>
        <div class="collapse" id="account-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-light rounded">Profile</a></li>
            <li><a href="#" class="link-light rounded">Settings</a></li>
            <li><partial name="_LoginPartial" /></li>
          </ul>
        </div>
      </li>*@
    </ul>
  </div>
     </div>


<div class="container">
    <h1>Edit</h1>
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-12">
                 <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input asp-for="MedsId" hidden />

                    <label asp-for="PatientId" class="control-label"></label>
                     <select asp-for="PatientId" class="form-control" asp-items="ViewBag.PatientId"></select>
                    <div class="form-group">
                        <label asp-for="MedicationOder" class="control-label"></label>
                        <input asp-for="MedicationOder" type="number" class="form-control" />
                        <span asp-validation-for="MedicationOder" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MedicationSubtotal" class="control-label"></label>
                        <input asp-for="MedicationSubtotal" class="form-control" />
                        <span asp-validation-for="MedicationSubtotal" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PickupDate" class="control-label"></label>
                        <input asp-for="PickupDate" class="form-control" />
                        <span asp-validation-for="PickupDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MediationStatus" class="control-label"></label>
                        <input asp-for="MediationStatus" class="form-control" />
                        <span asp-validation-for="MediationStatus" class="text-danger"></span>
                    </div>
                   <div class="form-group">
                        <label asp-for="Comments" class="control-label"></label>
                        <input asp-for="Comments" class="form-control" />
                        <span asp-validation-for="Comments" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Payment" class="control-label"></label>
                        <input asp-for="Payment" class="form-control" />
                        <span asp-validation-for="Payment" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PatientFullName" class="control-label"></label>
                        <input asp-for="PatientFullName" class="form-control" />
                        <span asp-validation-for="PatientFullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CoolectorFullNames" class="control-label"></label>
                        <input asp-for="CoolectorFullNames" class="form-control" />
                        <span asp-validation-for="CoolectorFullNames" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PlhoneNumbers" class="control-label"></label>
                        <input asp-for="PlhoneNumbers" class="form-control" />
                        <span asp-validation-for="PlhoneNumbers" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        @*<input type="submit" value="Create" class="btn btn-primary" />*@
                         <button id="registerSubmit" type="submit" class="btn btn-lg btn-primary button btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin: 10px 15px;">
                 Submit
                </button>
             </div>
        </form>
            </div>
        </div>
    </div>
</div>

Views/PickUpMeds/Index.cshtml
@model IEnumerable<ClinicalApp.Models.PickUpMedication>


<style>

.b-example-divider {
  flex-shrink: 0;
  width: 1.5rem;
  height: 100vh;
  background-color: rgba(0, 0, 0, .1);
  border: solid rgba(0, 0, 0, .15);
  border-width: 1px 0;
  box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
}

.bi {
  vertical-align: -.125em;
  pointer-events: none;
  fill: currentColor;
}

.dropdown-toggle { outline: 0; }

.nav-flush .nav-link {
  border-radius: 0;
}

.btn-toggle {
  display: inline-flex;
  align-items: center;
  padding: .25rem .5rem;
  font-weight: 600;
  color: rgba(0, 0, 0, .65);
  background-color: transparent;
  border: 0;
}
.btn-toggle:hover,
.btn-toggle:focus {
  color: rgba(0, 0, 0, .85);
  background-color: #d2f4ea;
}

.btn-toggle::before {
  width: 1.25em;
  line-height: 0;
  content: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='rgba%280,0,0,.5%29' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M5 14l6-6-6-6'/%3e%3c/svg%3e");
  transition: transform .35s ease;
  transform-origin: .5em 50%;
}

.btn-toggle[aria-expanded="true"] {
  color: rgba(0, 0, 0, .85);
}
.btn-toggle[aria-expanded="true"]::before {
  transform: rotate(90deg);
}

.btn-toggle-nav a {
  display: inline-flex;
  padding: .1875rem .5rem;
  margin-top: .125rem;
  margin-left: 1.25rem;
  text-decoration: none;
}
.btn-toggle-nav a:hover,
.btn-toggle-nav a:focus {
  background-color: #d2f4ea;
}

.scrollarea {
  overflow-y: auto;
}

.fw-semibold { font-weight: 600; }
.lh-tight { line-height: 1.25; }

.grids{
    display: flex;
    margin-top: -1%;
}


</style>


 <div class="grids">
     <div>
         <div class="flex-shrink-0 p-3 bg-dark" style="width: 280px; height: 100%;">
    <a asp-controller="Home" asp-action="Index" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-5 fw-semibold btn btn-success">L.H.M.S</span>
      <br /> 
    </a>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <a asp-controller="Dashboard" asp-action="Index" class="btn btn-outline-light">
          Home
        </a>
      </li>
     </ul>
      <ul class="btn-toggle-nav text-dark list-unstyled fw-normal pb-1 small">
            <li><a asp-controller="UserRole" asp-action="Index" class="link-light rounded"><i class="bi bi-people-fill"></i>&nbsp;&nbsp;Employees</a></li>
            <li><a asp-controller="Patient" asp-action="Index" class="link-light rounded"><i class="bi bi-hospital"></i>&nbsp;&nbsp;Patients</a></li>
            <li><a asp-controller="Chronic_Desease" asp-action="Index" class="link-light rounded"><i class="fa fa-bed"></i>&nbsp;&nbsp;Patient on merdication in hospital</a></li>
            

            <li><a asp-controller="Paramedic" asp-action="Index" class="link-light rounded"><i class="fas fa-ambulance"></i>&nbsp;&nbsp;Paramedics</a></li>
            <li><a asp-controller="Doctors" asp-action="Index"  class="link-light rounded"><i class="fas fa-user-md"></i>&nbsp;&nbsp;Doctors</a></li>
            <li><a asp-controller="Admin" asp-action="Index"  class="link-light rounded"><i class="bi bi-person-workspace"></i>&nbsp;&nbsp;Admin</a></li>
            <li><a asp-controller="IT" asp-action="Index" class="link-light rounded"><i class="bi bi-laptop"></i>&nbsp;&nbsp;IT</a></li>
            <li><a asp-controller="HR" asp-action="Index" class="link-light rounded"><i class="bi bi-person-check-fill"></i>&nbsp;&nbsp;HR</a></li>
             <li><a asp-controller="Clearner" asp-action="" class="link-light rounded"><i class="fas fa-hands-wash"></i>&nbsp;&nbsp;Cleaner</a></li>
            <li><a asp-controller="Nurse" asp-action="Index" class="link-light rounded"><i class="fas fa-user-nurse"></i>&nbsp;&nbsp;Nurses</a></li>
            <li><a asp-controller="Doctors" asp-action="Create" class="link-light rounded"><i class="fas fa-user-plus"></i>&nbsp;&nbsp;Add a Doctor</a></li>
            <li><a asp-controller="Finance" asp-action="Index" class="link-light rounded"><i class="bi bi-cash-coin"></i>&nbsp;&nbsp;Finance</a></li>
            <li><a asp-controller="Manager" asp-action="Index" class="link-light rounded"><i class="bi bi-list-task"></i>&nbsp;&nbsp;Management</a></li>
            <li><a asp-controller="Porter" asp-action="Index" class="link-light rounded"><i class="fa-solid fa-skull-crossbones"></i>&nbsp;&nbsp;Porter</a></li>

            <li><a asp-controller="P_Hospital" asp-action="Index" class="link-light rounded"><i class="fa fa-bed"></i>&nbsp;&nbsp;Patient on merdication of hospital</a></li>
            <li><a asp-controller="InComplete" asp-action="Index" class="link-light rounded"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>&nbsp;&nbsp;Patientwho didnt complete treatment</a></li>
            <li><a asp-controller="PickUpMeds" asp-action="Index" class="link-light rounded"><i class="bi bi-collection-fill"></i>&nbsp;&nbsp;Collection</a></li>
             <li><a asp-controller="MaleWards" asp-action="Index" class="link-light rounded"><i class="fas fa-male"></i>&nbsp;&nbsp;Male Ward</a></li>
            <li><a asp-controller="FemaleWards" asp-action="Index" class="link-light rounded"><i class="fas fa-female"></i>&nbsp;&nbsp;Female Ward</a></li>
            <li><a asp-controller="MetinityWard" asp-action="Index" class="link-light rounded"><i class="fas fa-baby"></i>&nbsp;&nbsp;Metinity Ward</a></li>
           
             

       
      <li class="border-top my-3"></li>
     @* <li class="mb-1">
        <button class="btn btn-toggle align-items-center bg-danger text-light rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
          Account
        </button>
        <div class="collapse" id="account-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-light rounded">Profile</a></li>
            <li><a href="#" class="link-light rounded">Settings</a></li>
            <li><partial name="_LoginPartial" /></li>
          </ul>
        </div>
      </li>*@
    </ul>
  </div>
     </div>


<div class="container" style="margin-top: 36px;">

<a asp-action="Create" class="btn btn-dark">Collector</a>

<table id="example" class="table table-hover table-striped table-bordered">
    <thead>
        <tr class="bg-dark text-light">
            <th>
                @Html.DisplayNameFor(model => model.PatientId)
            </th>
            <th>Medication Number</th>
            <th>
                Medication sub totoal
            </th>
            <th>
                Pick up date for medication
            </th>
            <th>
                Medication Status
            </th>
            <th>
                Comments
            </th>
            <th>
                Payments
            </th>
            <th>
                Patient Full Names
            </th>
            <th>
                Collector Full Names
            </th>
            <th>
                Phone Numbers
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PatientId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MedicationOder)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MedicationSubtotal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PickupDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MediationStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comments)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Payment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PatientFullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CoolectorFullNames)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlhoneNumbers)
                </td>
                <td>
                     <a asp-action="Edit" class="text-info" asp-route-id="@item.MedsId"><i class="fas fa-edit"></i></a>
                </td>
            </tr>
        }
        
    </tbody>
</table>

</div>



@section Scripts{
   <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>

 <script>
    $(document).ready(function() {
    $('#example').DataTable();
} );
 </script>
}