Models/Nurse.cs
using System.ComponentModel.DataAnnotations;

namespace ClinicalApp.Models
{
    public class Nurse
    {
        [Key]
        public int NurseId { get; set; }
        [Required(ErrorMessage = "First Name is required"), Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Last Name is required"), Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Email Addressis required"), Display(Name = "Email Address")]
        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "Home Address is required"), Display(Name = "Home Address")]
        public string HomeAddress { get; set; }
        [Required(ErrorMessage = "Phone Number is required"), Display(Name = "Phone Number"), MaxLength(10)]
        public string Phonenumber { get; set; }
        [Required(ErrorMessage = "Your photo is required!")]
        public string Image { get; set; }
    }
}

Controllers/NurseController.cs
using ClinicalApp.Interface;
using ClinicalApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ClinicalApp.Controllers
{
    public class NurseController : Controller
    {
        private readonly INurseRepository _nurse;
        private readonly IWebHostEnvironment _environment;

        public NurseController(INurseRepository nurse, IWebHostEnvironment environment)
        {
            _nurse = nurse;
            _environment = environment;
        }
        [Authorize(Roles = "Admin, Doctor, Nurse")]
        // GET: AdminController1
        public async Task<IActionResult> Index()
        {
            List<Nurse> nurse = _nurse.GetAll();
            return View(nurse);
        }

        // GET: AdminController1/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Nurse nurse = _nurse.GetById(id);
            return View(nurse);
        }

        // GET: AdminController1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AdminController1/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NurseId, FirstName, LastName, EmailAddress, HomeAddress, Phonenumber, Image")] Nurse nurse)
        {
            string webRootPath = _environment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            string fileName = Guid.NewGuid().ToString();
            var upload = Path.Combine(webRootPath, @"Images\Nurses\");
            var extention = Path.GetExtension(files[0].FileName);

            using (var fileStream = new FileStream(Path.Combine(upload, fileName + extention), FileMode.Create))
            {
                files[0].CopyTo(fileStream);
            }

            nurse.Image = @"\Images\Nurses\" + fileName + extention;

            _nurse.Create(nurse);
            TempData["success"] = "Nurse was added successfully to database";
            return RedirectToAction("Index");
        }

        // GET: AdminController1/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Nurse nurse = _nurse.GetById(id);
            return View(nurse);
        }

        // POST: AdminController1/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NurseId, FirstName, LastName, EmailAddress, HomeAddress, Phonenumber, Image")] Nurse nurse)
        {
            if (id != nurse.NurseId)
            {
                return NotFound();
            }

            nurse = _nurse.Update(nurse);
            TempData["success"] = "Nurse was updated successfully";
            return RedirectToAction(nameof(Index));
        }

        // GET: AdminController1/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Nurse nurse = _nurse.GetById(id);
            return View(nurse);
        }

        // POST: AdminController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Nurse nurse)
        {
            nurse = _nurse.Delete(nurse);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Nurse/Create.cshtml
@model ClinicalApp.Models.Nurse
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>

.b-example-divider {
  flex-shrink: 0;
  width: 1.5rem;
  height: 100vh;
  background-color: rgba(0, 0, 0, .1);
  border: solid rgba(0, 0, 0, .15);
  border-width: 1px 0;
  box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
}

.bi {
  vertical-align: -.125em;
  pointer-events: none;
  fill: currentColor;
}

.dropdown-toggle { outline: 0; }

.nav-flush .nav-link {
  border-radius: 0;
}

.btn-toggle {
  display: inline-flex;
  align-items: center;
  padding: .25rem .5rem;
  font-weight: 600;
  color: rgba(0, 0, 0, .65);
  background-color: transparent;
  border: 0;
}
.btn-toggle:hover,
.btn-toggle:focus {
  color: rgba(0, 0, 0, .85);
  background-color: #d2f4ea;
}

.btn-toggle::before {
  width: 1.25em;
  line-height: 0;
  content: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='rgba%280,0,0,.5%29' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M5 14l6-6-6-6'/%3e%3c/svg%3e");
  transition: transform .35s ease;
  transform-origin: .5em 50%;
}

.btn-toggle[aria-expanded="true"] {
  color: rgba(0, 0, 0, .85);
}
.btn-toggle[aria-expanded="true"]::before {
  transform: rotate(90deg);
}

.btn-toggle-nav a {
  display: inline-flex;
  padding: .1875rem .5rem;
  margin-top: .125rem;
  margin-left: 1.25rem;
  text-decoration: none;
}
.btn-toggle-nav a:hover,
.btn-toggle-nav a:focus {
  background-color: #d2f4ea;
}

.scrollarea {
  overflow-y: auto;
}

.fw-semibold { font-weight: 600; }
.lh-tight { line-height: 1.25; }

img{
    height: 125px;
    width: 125px;
    border-radius: 50px;
}

.grids{
    display: flex;
}
</style>


 <div class="grids">
     <div>
         <div class="flex-shrink-0 p-3 bg-dark" style="width: 280px; height: 100%;">
    <a asp-controller="Home" asp-action="Index" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-5 fw-semibold btn btn-success">L.H.M.S</span>
      <br /> 
    </a>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <a asp-controller="Dashboard" asp-action="Index" class="btn btn-outline-light">
          Home
        </a>
      </li>
     </ul>
      <ul class="btn-toggle-nav text-dark list-unstyled fw-normal pb-1 small">
            <li><a asp-controller="UserRole" asp-action="Index" class="link-light rounded"><i class="bi bi-people-fill"></i>&nbsp;&nbsp;Employees</a></li>
            <li><a asp-controller="Patient" asp-action="Index" class="link-light rounded"><i class="bi bi-hospital"></i>&nbsp;&nbsp;Patients</a></li>
            <li><a asp-controller="Chronic_Desease" asp-action="Index" class="link-light rounded"><i class="fa fa-bed"></i>&nbsp;&nbsp;Patient on merdication in hospital</a></li>
            

            <li><a asp-controller="Paramedic" asp-action="Index" class="link-light rounded"><i class="fas fa-ambulance"></i>&nbsp;&nbsp;Paramedics</a></li>
            <li><a asp-controller="Doctors" asp-action="Index"  class="link-light rounded"><i class="fas fa-user-md"></i>&nbsp;&nbsp;Doctors</a></li>
            <li><a asp-controller="Admin" asp-action="Index"  class="link-light rounded"><i class="bi bi-person-workspace"></i>&nbsp;&nbsp;Admin</a></li>
            <li><a asp-controller="IT" asp-action="Index" class="link-light rounded"><i class="bi bi-laptop"></i>&nbsp;&nbsp;IT</a></li>
            <li><a asp-controller="HR" asp-action="Index" class="link-light rounded"><i class="bi bi-person-check-fill"></i>&nbsp;&nbsp;HR</a></li>
             <li><a asp-controller="Clearner" asp-action="" class="link-light rounded"><i class="fas fa-hands-wash"></i>&nbsp;&nbsp;Cleaner</a></li>
            <li><a asp-controller="Nurse" asp-action="Index" class="link-light rounded"><i class="fas fa-user-nurse"></i>&nbsp;&nbsp;Nurses</a></li>
            <li><a asp-controller="Doctors" asp-action="Create" class="link-light rounded"><i class="fas fa-user-plus"></i>&nbsp;&nbsp;Add a Doctor</a></li>
            <li><a asp-controller="Finance" asp-action="Index" class="link-light rounded"><i class="bi bi-cash-coin"></i>&nbsp;&nbsp;Finance</a></li>
            <li><a asp-controller="Manager" asp-action="Index" class="link-light rounded"><i class="bi bi-list-task"></i>&nbsp;&nbsp;Management</a></li>
            <li><a asp-controller="Porter" asp-action="Index" class="link-light rounded"><i class="fa-solid fa-skull-crossbones"></i>&nbsp;&nbsp;Porter</a></li>

            <li><a asp-controller="P_Hospital" asp-action="Index" class="link-light rounded"><i class="fa fa-bed"></i>&nbsp;&nbsp;Patient on merdication of hospital</a></li>
            <li><a asp-controller="InComplete" asp-action="Index" class="link-light rounded"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>&nbsp;&nbsp;Patientwho didnt complete treatment</a></li>
            <li><a asp-controller="PickUpMeds" asp-action="Index" class="link-light rounded"><i class="bi bi-collection-fill"></i>&nbsp;&nbsp;Collection</a></li>
             <li><a asp-controller="MaleWards" asp-action="Index" class="link-light rounded"><i class="fas fa-male"></i>&nbsp;&nbsp;Male Ward</a></li>
            <li><a asp-controller="FemaleWards" asp-action="Index" class="link-light rounded"><i class="fas fa-female"></i>&nbsp;&nbsp;Female Ward</a></li>
            <li><a asp-controller="MetinityWard" asp-action="Index" class="link-light rounded"><i class="fas fa-baby"></i>&nbsp;&nbsp;Metinity Ward</a></li>
           
             

       
      <li class="border-top my-3"></li>
     @* <li class="mb-1">
        <button class="btn btn-toggle align-items-center bg-danger text-light rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
          Account
        </button>
        <div class="collapse" id="account-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-light rounded">Profile</a></li>
            <li><a href="#" class="link-light rounded">Settings</a></li>
            <li><partial name="_LoginPartial" /></li>
          </ul>
        </div>
      </li>*@
    </ul>
  </div>
     </div>


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly"></div>
                <div class="form-group">
                    <label asp-for="FirstName" class="form-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                 <div class="form-group">
                    <label asp-for="LastName" class="form-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                 <div class="form-group">
                    <label asp-for="EmailAddress" class="form-label"></label>
                    <input asp-for="EmailAddress" class="form-control" />
                    <span asp-validation-for="EmailAddress" class="text-danger"></span>
                </div>
                 <div class="form-group">
                    <label asp-for="HomeAddress" class="form-label"></label>
                    <input asp-for="HomeAddress" class="form-control" />
                    <span asp-validation-for="HomeAddress" class="text-danger"></span>
                </div>
                 <div class="form-group">
                    <label asp-for="Phonenumber" class="form-label"></label>
                    <input asp-for="Phonenumber" class="form-control" />
                    <span asp-validation-for="Phonenumber" class="text-danger"></span>
                </div>
                 <div class="form-group">
                    <label asp-for="Image" class="form-label"></label>
                    <input asp-for="Image" type="file" name="files" id="uploadFile" class="form-control" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                 <div class="form-group">
                    <input type="submit" value="Submit" class="btn btn-success" />
                </div>
             </form>
        </div>
    </div>
</div>

Views/Nurse/Delete.cshtml
@model ClinicalApp.Models.Nurse
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>

.b-example-divider {
  flex-shrink: 0;
  width: 1.5rem;
  height: 100vh;
  background-color: rgba(0, 0, 0, .1);
  border: solid rgba(0, 0, 0, .15);
  border-width: 1px 0;
  box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
}

.bi {
  vertical-align: -.125em;
  pointer-events: none;
  fill: currentColor;
}

.dropdown-toggle { outline: 0; }

.nav-flush .nav-link {
  border-radius: 0;
}

.btn-toggle {
  display: inline-flex;
  align-items: center;
  padding: .25rem .5rem;
  font-weight: 600;
  color: rgba(0, 0, 0, .65);
  background-color: transparent;
  border: 0;
}
.btn-toggle:hover,
.btn-toggle:focus {
  color: rgba(0, 0, 0, .85);
  background-color: #d2f4ea;
}

.btn-toggle::before {
  width: 1.25em;
  line-height: 0;
  content: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='rgba%280,0,0,.5%29' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M5 14l6-6-6-6'/%3e%3c/svg%3e");
  transition: transform .35s ease;
  transform-origin: .5em 50%;
}

.btn-toggle[aria-expanded="true"] {
  color: rgba(0, 0, 0, .85);
}
.btn-toggle[aria-expanded="true"]::before {
  transform: rotate(90deg);
}

.btn-toggle-nav a {
  display: inline-flex;
  padding: .1875rem .5rem;
  margin-top: .125rem;
  margin-left: 1.25rem;
  text-decoration: none;
}
.btn-toggle-nav a:hover,
.btn-toggle-nav a:focus {
  background-color: #d2f4ea;
}

.scrollarea {
  overflow-y: auto;
}

.fw-semibold { font-weight: 600; }
.lh-tight { line-height: 1.25; }

img{
    height: 125px;
    width: 125px;
    border-radius: 50px;
}

.grids{
    display: flex;
}
</style>


 <div class="grids">
     <div>
         <div class="flex-shrink-0 p-3 bg-dark" style="width: 280px; height: 100%;">
    <a asp-controller="Home" asp-action="Index" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-5 fw-semibold btn btn-success">L.H.M.S</span>
      <br /> 
    </a>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <a asp-controller="Dashboard" asp-action="Index" class="btn btn-outline-light">
          Home
        </a>
      </li>
     </ul>
      <ul class="btn-toggle-nav text-dark list-unstyled fw-normal pb-1 small">
            <li><a asp-controller="UserRole" asp-action="Index" class="link-light rounded"><i class="bi bi-people-fill"></i>&nbsp;&nbsp;Employees</a></li>
            <li><a asp-controller="Patient" asp-action="Index" class="link-light rounded"><i class="bi bi-hospital"></i>&nbsp;&nbsp;Patients</a></li>
            <li><a asp-controller="Chronic_Desease" asp-action="Index" class="link-light rounded"><i class="fa fa-bed"></i>&nbsp;&nbsp;Patient on merdication in hospital</a></li>
            

            <li><a asp-controller="Paramedic" asp-action="Index" class="link-light rounded"><i class="fas fa-ambulance"></i>&nbsp;&nbsp;Paramedics</a></li>
            <li><a asp-controller="Doctors" asp-action="Index"  class="link-light rounded"><i class="fas fa-user-md"></i>&nbsp;&nbsp;Doctors</a></li>
            <li><a asp-controller="Admin" asp-action="Index"  class="link-light rounded"><i class="bi bi-person-workspace"></i>&nbsp;&nbsp;Admin</a></li>
            <li><a asp-controller="IT" asp-action="Index" class="link-light rounded"><i class="bi bi-laptop"></i>&nbsp;&nbsp;IT</a></li>
            <li><a asp-controller="HR" asp-action="Index" class="link-light rounded"><i class="bi bi-person-check-fill"></i>&nbsp;&nbsp;HR</a></li>
             <li><a asp-controller="Clearner" asp-action="" class="link-light rounded"><i class="fas fa-hands-wash"></i>&nbsp;&nbsp;Cleaner</a></li>
            <li><a asp-controller="Nurse" asp-action="Index" class="link-light rounded"><i class="fas fa-user-nurse"></i>&nbsp;&nbsp;Nurses</a></li>
            <li><a asp-controller="Doctors" asp-action="Create" class="link-light rounded"><i class="fas fa-user-plus"></i>&nbsp;&nbsp;Add a Doctor</a></li>
            <li><a asp-controller="Finance" asp-action="Index" class="link-light rounded"><i class="bi bi-cash-coin"></i>&nbsp;&nbsp;Finance</a></li>
            <li><a asp-controller="Manager" asp-action="Index" class="link-light rounded"><i class="bi bi-list-task"></i>&nbsp;&nbsp;Management</a></li>
            <li><a asp-controller="Porter" asp-action="Index" class="link-light rounded"><i class="fa-solid fa-skull-crossbones"></i>&nbsp;&nbsp;Porter</a></li>

            <li><a asp-controller="P_Hospital" asp-action="Index" class="link-light rounded"><i class="fa fa-bed"></i>&nbsp;&nbsp;Patient on merdication of hospital</a></li>
            <li><a asp-controller="InComplete" asp-action="Index" class="link-light rounded"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>&nbsp;&nbsp;Patientwho didnt complete treatment</a></li>
            <li><a asp-controller="PickUpMeds" asp-action="Index" class="link-light rounded"><i class="bi bi-collection-fill"></i>&nbsp;&nbsp;Collection</a></li>
             <li><a asp-controller="MaleWards" asp-action="Index" class="link-light rounded"><i class="fas fa-male"></i>&nbsp;&nbsp;Male Ward</a></li>
            <li><a asp-controller="FemaleWards" asp-action="Index" class="link-light rounded"><i class="fas fa-female"></i>&nbsp;&nbsp;Female Ward</a></li>
            <li><a asp-controller="MetinityWard" asp-action="Index" class="link-light rounded"><i class="fas fa-baby"></i>&nbsp;&nbsp;Metinity Ward</a></li>
           
             

       
      <li class="border-top my-3"></li>
     @* <li class="mb-1">
        <button class="btn btn-toggle align-items-center bg-danger text-light rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
          Account
        </button>
        <div class="collapse" id="account-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-light rounded">Profile</a></li>
            <li><a href="#" class="link-light rounded">Settings</a></li>
            <li><partial name="_LoginPartial" /></li>
          </ul>
        </div>
      </li>*@
    </ul>
  </div>
     </div>


<div class="container">
    <h1>Delete</h1>
    <div class="row">
        <div class="col-md-10">
            <dl class="row">
                <dt class="col-sm-12">
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.FirstName)
                </dd>
                 <dt class="col-sm-12">
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.LastName)
                </dd>
                 <dt class="col-sm-12">
                    @Html.DisplayNameFor(model => model.EmailAddress)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.EmailAddress)
                </dd>
                 <dt class="col-sm-12">
                    @Html.DisplayNameFor(model => model.HomeAddress)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.HomeAddress)
                </dd>
                 <dt class="col-sm-12">
                    @Html.DisplayNameFor(model => model.Phonenumber)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Phonenumber)
                </dd>
                 @*<dt class="col-sm-12">
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>*@
                <dd class="col-sm-10">
                    <img src="@Html.DisplayFor(model => model.Image)" />
                </dd>
            </dl>
            <form asp-action="delete">
                <input type="hidden" asp-for="NurseId" />
                <input type="submit" class="btn btn-danger" onclick="delete()" value="Delete" />
                <a asp-action="Index" class="btn btn-primary">Back</a>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    function delete(){
        alert("Are you sure you want to delete this record?")
    }
</script>