Models/InComplete.cs
using System.ComponentModel.DataAnnotations;

namespace ClinicalApp.Models
{
    public class InComplete
    {
        public int Id { get; set; }
        public string PatientFirstName { get; set; }
        [Required(ErrorMessage = "Patient Lats name is required"), Display(Name = "Patient Last Name")]
        public string PatientLastName { get; set; }
        [Required, Display(Name = "Date of Birth")]
        public DateTime DateOfBirth { get; set; }
        [Required, Display(Name = "Birth ID")]
        public string? BirthId { get; set; }
        [Required(ErrorMessage = "Patient contact number is required"), Display(Name = "Patient Contact Number")]
        public string ContactNumber { get; set; }
        [Required(ErrorMessage = "Email address is required"), Display(Name = "Emaill address")]
        public string EmailAddress { get; set; }
        [Required(ErrorMessage = "Home address is required"), Display(Name = "Home address")]
        public string HomeAddress { get; set; }
        [Display(Name = "Admit Status eg Admitted/Discharged")]
        public string AdmitStatus { get; set; }
        [Display(Name = "Passport Number")]
        public string PassportNumber { get; set; }
        [Display(Name = "Country of birth")]
        public string Country { get; set; }
        [Display(Name = "Reason for visittation in South Africa")]
        public string ReasonForVisitation { get; set; }
        [Display(Name = "Duration of visitiation in South Africa")]
        public string DurationOfVisitation { get; set; }
        [Display(Name = "Ward Name")]
        public string Ward_Name { get; set; }
        [Display(Name = "Date of admition")]
        public string DateOfAdmition { get; set; }
        [Display(Name = "Date of discharge")]
        public string DateOfDischarge { get; set; }
        [Required, Display(Name = "Benefit and risk of treatment")]
        public string BenefitOfTreatment { get; set; }
        [Required, Display(Name = "Risk Of Treatment if not taken")]
        public string RiskOfTreatment { get; set; }
        [Required, Display(Name = "Start time of treatment")]
        public DateTime StartOfTreatment { get; set; }
        [Required, Display(Name = "End of Treatment")]
        public DateTime EndOfTreatment { get; set; }
        [Display(Name = "Treatment statsu eg: Completed, Incoplete or on medication")]
        public string TreeatmentStatus { get; set; }
        [Required(ErrorMessage = "Patient status is required"), Display(Name = "Patient status")]
        public PatientStatus PatientStatus { get; set; }
        [Required]
        public Infection Infection { get; set; }
        [Required]
        public Illness Illness { get; set; }
        [Required, Display(Name = "Are there recovery chances?")]
        public string RecoveryChances { get; set; }
        [Required, Display(Name = "Does a patient require treatment?")]
        public string RecommendedTreatment { get; set; }
        [Required, Display(Name = "Can a patient survive if treatment is taken?")]
        public SuucessOfRecoveryIftreatmentTaken SuucessOfRecoveryIftreatmentTaken { get; set; }
    }
}

Controllers/InCompleteController.cs
using ClinicalApp.Data;
using ClinicalApp.Interface;
using ClinicalApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ClinicalApp.Controllers
{
    public class InCompleteController : Controller
    {
        private readonly IInComplteRepository _file;
        private readonly DatabaseContext _context;
        public InCompleteController(IInComplteRepository file, DatabaseContext context)
        {
            _file = file;
            _context = context;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            List<InComplete> file = _file.GetAll();
            return View(file);
        }

        [Authorize(Roles = ("Admin"))]
        // GET: Prescriptions/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            InComplete file = _file.GetById(id);
            if (file == null)
            {
                return NotFound();
            }
            return View(file);
        }

        // POST: Prescriptions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DoctorId,PatientFirstName,DateOfBirth, BirthId,PatientLastName,ContactNumber,EmailAddress,HomeAddress,PassportNumber,Country,TreeatmentStatus,ReasonForVisitation,DurationOfVisitation,AdmitStatus,Ward_Name,DateOfAdmition,DateOfDischarge,BenefitOfTreatment,RiskOfTreatment,StartOfTreatment,EndOfTreatment,PatientStatus,Infection,Illness,RecoveryChances,RecommendedTreatment,SucessOfRecoveryIftreatmentTaken")] InComplete hos)
        {
            if (id == null)
            {
                return NotFound();
            }
                _file.Update(hos);
                TempData["success"] = "Patient was updated successfully";

            return RedirectToAction(nameof(Index));
            return View(hos);
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            InComplete hos = _file.GetById(id);
            return View(hos);
        }

        // POST: AdminController1/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(InComplete hos)
        {
            hos = _file.DeleteById(hos);
            return RedirectToAction(nameof(Index));
        }

    }
}

Views/InComplete/Delete.cshtml
@model ClinicalApp.Models.InComplete

<style>
     .header{
        min-width: 100vh;
        width: 100%;
        background-image: linear-gradient(rgba(13, 202, 240, 0.5), rgba(13, 202, 240, 0.5)), url("https://newsroom.uw.edu/sites/default/files/bioethics-elderly-crisis-care.png");
        background-position: center;
        background-size: cover;
        position: relative;
        margin-top: -1.3%;
        height: 100vh;
    }
   
    .home{
        padding: 20%;
    }

    .home h1{
        margin-left: 3%;
        font-weight: 700;
        font-size: 3.8em;
        font-family:'Times New Roman', Times, serif;
    }

    .mb{
        font-weight: 500;
        font-size: 1.1em;
        color: orangered;
        margin-left: 20px;
    }

    button{
        margin-left: 20px;
    }

.b-example-divider {
  flex-shrink: 0;
  width: 1.5rem;
  height: 100vh;
  background-color: rgba(0, 0, 0, .1);
  border: solid rgba(0, 0, 0, .15);
  border-width: 1px 0;
  box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
}

.bi {
  vertical-align: -.125em;
  pointer-events: none;
  fill: currentColor;
}

.dropdown-toggle { outline: 0; }

.nav-flush .nav-link {
  border-radius: 0;
}

.btn-toggle {
  display: inline-flex;
  align-items: center;
  padding: .25rem .5rem;
  font-weight: 600;
  color: rgba(0, 0, 0, .65);
  background-color: transparent;
  border: 0;
}
.btn-toggle:hover,
.btn-toggle:focus {
  color: rgba(0, 0, 0, .85);
  background-color: #d2f4ea;
}

.btn-toggle::before {
  width: 1.25em;
  line-height: 0;
  content: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='rgba%280,0,0,.5%29' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M5 14l6-6-6-6'/%3e%3c/svg%3e");
  transition: transform .35s ease;
  transform-origin: .5em 50%;
}

.btn-toggle[aria-expanded="true"] {
  color: rgba(0, 0, 0, .85);
}
.btn-toggle[aria-expanded="true"]::before {
  transform: rotate(90deg);
}

.btn-toggle-nav a {
  display: inline-flex;
  padding: .1875rem .5rem;
  margin-top: .125rem;
  margin-left: 1.25rem;
  text-decoration: none;
}
.btn-toggle-nav a:hover,
.btn-toggle-nav a:focus {
  background-color: #d2f4ea;
}

.scrollarea {
  overflow-y: auto;
}

.fw-semibold { font-weight: 600; }
.lh-tight { line-height: 1.25; }

img{
    height: 125px;
    width: 125px;
    border-radius: 50px;
}

.grids{
    display: flex;
}

#foreignInfo, #discharging{
    display: none;
}
</style>


 <div class="grids">
     <div>
         <div class="flex-shrink-0 p-3 bg-dark" style="width: 280px; height: 100%;">
    <a asp-controller="Home" asp-action="Index" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-5 fw-semibold btn btn-success">L.H.M.S</span>
      <br /> 
    </a>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <a asp-controller="Dashboard" asp-action="Index" class="btn btn-outline-light">
          Home
        </a>
      </li>
     </ul>
      <ul class="btn-toggle-nav text-dark list-unstyled fw-normal pb-1 small">
            <li><a asp-controller="UserRole" asp-action="Index" class="link-light rounded"><i class="bi bi-people-fill"></i>&nbsp;&nbsp;Employees</a></li>
            <li><a asp-controller="Patient" asp-action="Index" class="link-light rounded"><i class="bi bi-hospital"></i>&nbsp;&nbsp;Patients</a></li>
            <li><a asp-controller="Chronic_Desease" asp-action="Index" class="link-light rounded"><i class="fa fa-bed"></i>&nbsp;&nbsp;Patient on merdication in hospital</a></li>
            

            <li><a asp-controller="Paramedic" asp-action="Index" class="link-light rounded"><i class="fas fa-ambulance"></i>&nbsp;&nbsp;Paramedics</a></li>
            <li><a asp-controller="Doctors" asp-action="Index"  class="link-light rounded"><i class="fas fa-user-md"></i>&nbsp;&nbsp;Doctors</a></li>
            <li><a asp-controller="Admin" asp-action="Index"  class="link-light rounded"><i class="bi bi-person-workspace"></i>&nbsp;&nbsp;Admin</a></li>
            <li><a asp-controller="IT" asp-action="Index" class="link-light rounded"><i class="bi bi-laptop"></i>&nbsp;&nbsp;IT</a></li>
            <li><a asp-controller="HR" asp-action="Index" class="link-light rounded"><i class="bi bi-person-check-fill"></i>&nbsp;&nbsp;HR</a></li>
             <li><a asp-controller="Clearner" asp-action="" class="link-light rounded"><i class="fas fa-hands-wash"></i>&nbsp;&nbsp;Cleaner</a></li>
            <li><a asp-controller="Nurse" asp-action="Index" class="link-light rounded"><i class="fas fa-user-nurse"></i>&nbsp;&nbsp;Nurses</a></li>
            <li><a asp-controller="Doctors" asp-action="Create" class="link-light rounded"><i class="fas fa-user-plus"></i>&nbsp;&nbsp;Add a Doctor</a></li>
            <li><a asp-controller="Finance" asp-action="Index" class="link-light rounded"><i class="bi bi-cash-coin"></i>&nbsp;&nbsp;Finance</a></li>
            <li><a asp-controller="Manager" asp-action="Index" class="link-light rounded"><i class="bi bi-list-task"></i>&nbsp;&nbsp;Management</a></li>
            <li><a asp-controller="Porter" asp-action="Index" class="link-light rounded"><i class="fa-solid fa-skull-crossbones"></i>&nbsp;&nbsp;Porter</a></li>

            <li><a asp-controller="P_Hospital" asp-action="Index" class="link-light rounded"><i class="fa fa-bed"></i>&nbsp;&nbsp;Patient on merdication of hospital</a></li>
            <li><a asp-controller="InComplete" asp-action="Index" class="link-light rounded"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>&nbsp;&nbsp;Patientwho didnt complete treatment</a></li>
            <li><a asp-controller="PickUpMeds" asp-action="Index" class="link-light rounded"><i class="bi bi-collection-fill"></i>&nbsp;&nbsp;Collection</a></li>
             <li><a asp-controller="MaleWards" asp-action="Index" class="link-light rounded"><i class="fas fa-male"></i>&nbsp;&nbsp;Male Ward</a></li>
            <li><a asp-controller="FemaleWards" asp-action="Index" class="link-light rounded"><i class="fas fa-female"></i>&nbsp;&nbsp;Female Ward</a></li>
            <li><a asp-controller="MetinityWard" asp-action="Index" class="link-light rounded"><i class="fas fa-baby"></i>&nbsp;&nbsp;Metinity Ward</a></li>
           
             

       
      <li class="border-top my-3"></li>
     @* <li class="mb-1">
        <button class="btn btn-toggle align-items-center bg-danger text-light rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
          Account
        </button>
        <div class="collapse" id="account-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-light rounded">Profile</a></li>
            <li><a href="#" class="link-light rounded">Settings</a></li>
            <li><partial name="_LoginPartial" /></li>
          </ul>
        </div>
      </li>*@
    </ul>
  </div>
     </div>



     <section class="header">
    <div class="home">
          <h1 class="text-danger">L.H.M.S <small>Patients</small></h1>
            <p class="col-md-7 mb text-light">Has the patient defaulted on his previous condition? Patient name/s: <strong class="text-danger">@Html.DisplayFor(model => model.PatientFirstName) @Html.DisplayFor(model => model.PatientLastName). Is the patient admitted again? </strong></p>
             <form asp-action="Delete">
       <input type="hidden" asp-for="Id" />
       <input type="submit" value="Yes" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin: 10px 15px;"/> 
        <a asp-action="Index" class="btn btn-dark">Wrong patient</a>
 </form>
       
    </div>
</section>


 

</div>

@section Scripts{
    <script>
        function showhideInput(){
                if(document.getElementById('foreign').checked == "Yes"){
                     document.getElementById('foreignInfo').style.display = 'none';
                }
                else{
                    document.getElementById('foreignInfo').style.display = 'block';
                }

        }        
    </script>
    <script>
        
                function patientDischarge(){
                    if(document.getElementById('discharge').checked == "Yes"){
                        document.getElementById('discharging').style.display = "none";
                    }
                    else{
                        document.getElementById('discharging').style.display = "block";
                    }
                }
    </script>
}

Views/InComplete/Index.cshtml
@model IEnumerable<ClinicalApp.Models.InComplete>

@{
    ViewData["Title"] = "Index";
}

<style>

.b-example-divider {
  flex-shrink: 0;
  width: 1.5rem;
  height: 100vh;
  background-color: rgba(0, 0, 0, .1);
  border: solid rgba(0, 0, 0, .15);
  border-width: 1px 0;
  box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
}

.bi {
  vertical-align: -.125em;
  pointer-events: none;
  fill: currentColor;
}

.dropdown-toggle { outline: 0; }

.nav-flush .nav-link {
  border-radius: 0;
}

.btn-toggle {
  display: inline-flex;
  align-items: center;
  padding: .25rem .5rem;
  font-weight: 600;
  color: rgba(0, 0, 0, .65);
  background-color: transparent;
  border: 0;
}
.btn-toggle:hover,
.btn-toggle:focus {
  color: rgba(0, 0, 0, .85);
  background-color: #d2f4ea;
}

.btn-toggle::before {
  width: 1.25em;
  line-height: 0;
  content: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 16 16'%3e%3cpath fill='none' stroke='rgba%280,0,0,.5%29' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M5 14l6-6-6-6'/%3e%3c/svg%3e");
  transition: transform .35s ease;
  transform-origin: .5em 50%;
}

.btn-toggle[aria-expanded="true"] {
  color: rgba(0, 0, 0, .85);
}
.btn-toggle[aria-expanded="true"]::before {
  transform: rotate(90deg);
}

.btn-toggle-nav a {
  display: inline-flex;
  padding: .1875rem .5rem;
  margin-top: .125rem;
  margin-left: 1.25rem;
  text-decoration: none;
}
.btn-toggle-nav a:hover,
.btn-toggle-nav a:focus {
  background-color: #d2f4ea;
}

.scrollarea {
  overflow-y: auto;
}

.fw-semibold { font-weight: 600; }
.lh-tight { line-height: 1.25; }

.grids{
    display: flex;
    margin-top: -1%;
}

</style>


 <div class="grids">
     <div>
         <div class="flex-shrink-0 p-3 bg-dark" style="width: 280px; height: 100%;">
    <a asp-controller="Home" asp-action="Index" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-5 fw-semibold btn btn-success">L.H.M.S</span>
      <br /> 
    </a>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <a asp-controller="Dashboard" asp-action="Index" class="btn btn-outline-light">
          Home
        </a>
      </li>
     </ul>
      <ul class="btn-toggle-nav text-dark list-unstyled fw-normal pb-1 small">
            <li><a asp-controller="UserRole" asp-action="Index" class="link-light rounded"><i class="bi bi-people-fill"></i>&nbsp;&nbsp;Employees</a></li>
            <li><a asp-controller="Patient" asp-action="Index" class="link-light rounded"><i class="bi bi-hospital"></i>&nbsp;&nbsp;Patients</a></li>
            <li><a asp-controller="Chronic_Desease" asp-action="Index" class="link-light rounded"><i class="fa fa-bed"></i>&nbsp;&nbsp;Patient on merdication in hospital</a></li>
            

            <li><a asp-controller="Paramedic" asp-action="Index" class="link-light rounded"><i class="fas fa-ambulance"></i>&nbsp;&nbsp;Paramedics</a></li>
            <li><a asp-controller="Doctors" asp-action="Index"  class="link-light rounded"><i class="fas fa-user-md"></i>&nbsp;&nbsp;Doctors</a></li>
            <li><a asp-controller="Admin" asp-action="Index"  class="link-light rounded"><i class="bi bi-person-workspace"></i>&nbsp;&nbsp;Admin</a></li>
            <li><a asp-controller="IT" asp-action="Index" class="link-light rounded"><i class="bi bi-laptop"></i>&nbsp;&nbsp;IT</a></li>
            <li><a asp-controller="HR" asp-action="Index" class="link-light rounded"><i class="bi bi-person-check-fill"></i>&nbsp;&nbsp;HR</a></li>
             <li><a asp-controller="Clearner" asp-action="" class="link-light rounded"><i class="fas fa-hands-wash"></i>&nbsp;&nbsp;Cleaner</a></li>
            <li><a asp-controller="Nurse" asp-action="Index" class="link-light rounded"><i class="fas fa-user-nurse"></i>&nbsp;&nbsp;Nurses</a></li>
            <li><a asp-controller="Doctors" asp-action="Create" class="link-light rounded"><i class="fas fa-user-plus"></i>&nbsp;&nbsp;Add a Doctor</a></li>
            <li><a asp-controller="Finance" asp-action="Index" class="link-light rounded"><i class="bi bi-cash-coin"></i>&nbsp;&nbsp;Finance</a></li>
            <li><a asp-controller="Manager" asp-action="Index" class="link-light rounded"><i class="bi bi-list-task"></i>&nbsp;&nbsp;Management</a></li>
            <li><a asp-controller="Porter" asp-action="Index" class="link-light rounded"><i class="fa-solid fa-skull-crossbones"></i>&nbsp;&nbsp;Porter</a></li>

            <li><a asp-controller="P_Hospital" asp-action="Index" class="link-light rounded"><i class="fa fa-bed"></i>&nbsp;&nbsp;Patient on merdication of hospital</a></li>
            <li><a asp-controller="InComplete" asp-action="Index" class="link-light rounded"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>&nbsp;&nbsp;Patientwho didnt complete treatment</a></li>
            <li><a asp-controller="PickUpMeds" asp-action="Index" class="link-light rounded"><i class="bi bi-collection-fill"></i>&nbsp;&nbsp;Collection</a></li>
             <li><a asp-controller="MaleWards" asp-action="Index" class="link-light rounded"><i class="fas fa-male"></i>&nbsp;&nbsp;Male Ward</a></li>
            <li><a asp-controller="FemaleWards" asp-action="Index" class="link-light rounded"><i class="fas fa-female"></i>&nbsp;&nbsp;Female Ward</a></li>
            <li><a asp-controller="MetinityWard" asp-action="Index" class="link-light rounded"><i class="fas fa-baby"></i>&nbsp;&nbsp;Metinity Ward</a></li>
           
             

       
      <li class="border-top my-3"></li>
     @* <li class="mb-1">
        <button class="btn btn-toggle align-items-center bg-danger text-light rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
          Account
        </button>
        <div class="collapse" id="account-collapse">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-light rounded">Profile</a></li>
            <li><a href="#" class="link-light rounded">Settings</a></li>
            <li><partial name="_LoginPartial" /></li>
          </ul>
        </div>
      </li>*@
    </ul>
  </div>
     </div>

     <div class="container" style="margin-top: 36px;">

<table id="example" class="table table-hover table-stiped table-bordered">
    <thead>
        <tr class="bg-dark text-light">
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Date Of Birth
            </th>
            <th>
                Contact Number
            </th>
            <th>
                Email Address
            </th>
            <th>
               Date Of Admition
            </th>
            <th>
               Discharged date
            </th>
            <th>Ward</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PatientFirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PatientLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddress)
            </td>
              <td>
                @Html.DisplayFor(modelItem => item.DateOfAdmition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfDischarge)
            </td>
            <td>
                 @Html.DisplayFor(modelItem => item.Ward_Name)
                @* *@
            </td>
            <td>
               <a asp-action="Edit" class="btn btn-info" asp-route-id="@item.Id"><i class="fas fa-edit"></i></a>
                <a asp-action="Delete" class="btn btn-dark" asp-route-id="@item.Id"><i class="bi bi-folder-x"></i></a>
             </td>
        </tr>
}
    </tbody>
</table>

     </div>
 </div>

 <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>

 <script>
    $(document).ready(function() {
    $('#example').DataTable();
} );
 </script>